name: Deploy Development

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: 0
      DATABASE_URL: postgres://user:pass@localhost/test_db
      SECRET_KEY: somesecrete
      ENVIRONMENT: dev

    services:
      postgres:
        image: 'postgres:alpine'
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test_db
        volumes:
          - 'db-data:/var/lib/postgresql/data'
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements/dev.txt

      - name: Run migrations
      
        run: |
          python app/manage.py makemigrations
          python app/manage.py migrate

      - name: Run Tests
        run: |
          pytest 

      - name: Push to server and deploy
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: '${{secrets.HEROKU_API_KEY}}'
          heroku_app_name: '${{ secrets.HEROKU_APP_NAME }}'
          heroku_email: '${{ secrets.HEROKU_EMAIL_ADDRESS }}'
